### ISSUE TITLE
Easter Egg

### ISSUE THREAD

**Issue by matthewxing1** [oslabs-beta/ksqlSuite#75]
I really dislike ggbong's last name, can we change it?

**Comment by ggbong734** [comment]
umm sorry no bueno

**Comment by jonathanluu17** [comment]
This has been an ongoing issue for a while I believe. Have you tried contacting the devs?

**Comment by matthewxing1** [comment]
Yes I have, I AM the dev

**Comment by javanang** [comment]
have you read the readme yet?

**Comment by matthewxing1** [comment]
Oh I have not, thank you for your insight

**Comment by matthewxing1** [comment]
I am back, the readme did not help with my complaint. Escalating the issue

**Comment by javanang** [comment]
have you tried restarting your computer?

**Comment by matthewxing1** [comment]
That seems excessive, however I see the practicality of it. I will give this a try

**Comment by matthewxing1** [comment]
I am back to report that my issue has been solved - restarting my computer broaded my worldview and I am now more trusting of ggbong's last name, although I still harbor some suspicious. Thank you for your help Javan!

**Comment by ggbong734** [comment]
This issue seems isolated to certain Windows environments. Can I suggest running it in Linux using WSL?
